### ISSUE TITLE
investigate test failure: character concat

### ISSUE THREAD

**Issue by johnynek** [typelevel/paiges#45]
```
[info] - character concat works *** FAILED *** (44 milliseconds)
[info]   TestFailedException was thrown during property evaluation.
[info]     Message: -1 did not equal 0
[info]     Location: (PaigesTest.scala:452)
[info]     Occurred when passed generated values (
[info]       arg0 = '┉',
[info]       arg1 = '
[info]   '
[info]     )
[info]   Cause: org.scalatest.exceptions.TestFailedException: -1 did not equal 0
[info]   at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:528)
[info]   at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:527)
[info]   at org.scalatest.FunSuite.newAssertionFailedException(FunSuite.scala:1560)
[info]   at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:501)
[info]   at org.typelevel.paiges.PaigesTest.$anonfun$new$101(PaigesTest.scala:452)
[info]   at org.typelevel.paiges.PaigesTest.$anonfun$new$101$adapted(PaigesTest.scala:449)
[info]   at org.typelevel.paiges.PaigesTest$$Lambda$2102/59670239.apply(Unknown Source)
[info]   at org.scalatest.prop.GeneratorDrivenPropertyChecks.liftedTree11$1(GeneratorDrivenPropertyChecks.scala:1028)
```

**Comment by johnynek** [comment]
looks like newline is mishandled.
